import { Note } from './types';

export function generatePowerShellScript(notes: Note[], bpm: number): string {
  if (notes.length === 0) return '';

  const ms_per_beat = 60000 / bpm;
  const scriptLines: string[] = [];

  scriptLines.push('# PowerShell Music Script generated by Tauri App');
  scriptLines.push(`$BPM = ${bpm}`);
  scriptLines.push('');

  const hasSynth = notes.some(n => n.synth_type === 'synth');

  if (hasSynth) {
    scriptLines.push(`
# Initialize C# class for WinMM MIDI support
$csharpCode = @"
using System;
using System.Runtime.InteropServices;

public class MidiPlayer {
    [DllImport("winmm.dll")]
    public static extern uint midiOutOpen(out IntPtr lphMidiOut, uint uDeviceID, IntPtr dwCallback, IntPtr dwInstance, uint dwFlags);

    [DllImport("winmm.dll")]
    public static extern uint midiOutClose(IntPtr hMidiOut);

    [DllImport("winmm.dll")]
    public static extern uint midiOutShortMsg(IntPtr hMidiOut, uint dwMsg);
}
"@

Add-Type -TypeDefinition $csharpCode -Language CSharp
$midiHandle = [IntPtr]::Zero
[MidiPlayer]::midiOutOpen([ref]$midiHandle, 0, [IntPtr]::Zero, [IntPtr]::Zero, 0) | Out-Null

# Change Program to Microsoft GS Wavetable Synth (usually program 0)
[MidiPlayer]::midiOutShortMsg($midiHandle, 0x0000C0) | Out-Null
`);
  }

  // To support polyphony, we break notes into distinct events
  interface MidiEvent {
    beat: number;
    type: 'on' | 'off';
    note: Note;
  }

  const events: MidiEvent[] = [];

  for (const note of notes) {
    if (note.synth_type === 'beep') {
      // For beep, we just schedule a blocking event
      events.push({ beat: note.start_beat, type: 'on', note });
    } else {
      events.push({ beat: note.start_beat, type: 'on', note });
      events.push({ beat: note.start_beat + note.duration_beat, type: 'off', note });
    }
  }

  // Sort events primarily by time.
  events.sort((a, b) => {
    if (a.beat !== b.beat) return a.beat - b.beat;
    // Process Note Offs before Note Ons at the exact same time
    if (a.type !== b.type) return a.type === 'off' ? -1 : 1;
    return 0;
  });

  let current_beat = 0;

  for (const event of events) {
    if (event.beat > current_beat) {
      const gap_ms = Math.round((event.beat - current_beat) * ms_per_beat);
      scriptLines.push(`Start-Sleep -Milliseconds ${gap_ms}`);
      current_beat = event.beat;
    }

    if (event.note.synth_type === 'beep' && event.type === 'on') {
      const duration_ms = Math.round(event.note.duration_beat * ms_per_beat);
      const freq = Math.round(440 * Math.pow(2, (event.note.pitch - 69) / 12));
      scriptLines.push(`[console]::beep(${freq}, ${duration_ms})`);
      current_beat += event.note.duration_beat;
    } else if (event.note.synth_type === 'synth') {
      if (event.type === 'on') {
        const noteOnMsg = 0x007F0090 | (event.note.pitch << 8); // Velocity 127
        scriptLines.push(`[MidiPlayer]::midiOutShortMsg($midiHandle, ${noteOnMsg}) | Out-Null`);
      } else {
        const noteOffMsg = 0x00000080 | (event.note.pitch << 8); // Velocity 0
        scriptLines.push(`[MidiPlayer]::midiOutShortMsg($midiHandle, ${noteOffMsg}) | Out-Null`);
      }
    }
  }

  if (hasSynth) {
    scriptLines.push(`
# Close MIDI device
[MidiPlayer]::midiOutClose($midiHandle) | Out-Null
`);
  }

  return scriptLines.join('\n');
}
